security:
    role_hierarchy:
        ROLE_MOD: ROLE_USER
        ROLE_ADMIN: ROLE_MOD

    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
