security:
    role_hierarchy:
        ROLE_MOD: ROLE_USER
        ROLE_ADMIN: ROLE_MOD

    providers:
        google_oauth.provider:
            entity: { class: AppBundle\Entity\User, property: email }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        user_area:
            security: true
            pattern: ^/
            anonymous: ~
            provider: google_oauth.provider
            access_denied_url: /error/403