security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        hvz_user_provider:
            entity: { class: HvzGameBundle:User, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        user_area:
            security: true
            pattern: ^/
            anonymous: ~
            provider: hvz_user_provider
            google_oauth: true
            access_denied_url: /error/403

    access_control:
        #- { path: ^/auth/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/auth/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/admin, roles: ROLE_ADMIN }
