# Game\Status Controller
hvz_index:
    pattern: /
    defaults: { _controller: HvzGameBundle:Game/Status:index }

hvz_error_game:
    pattern: /error/game
    defaults: { _controller: HvzGameBundle:Game/Status:gameError }

# Game\Rules Controller
hvz_rules:
    pattern: /rules
    defaults: { _controller: HvzGameBundle:Game/Rules:index }

# Game\Register Tag Controller
hvz_register_tag:
    pattern: /register_tag
    defaults: { _controller: HvzGameBundle:Game/RegisterTag:index }
    methods: [GET]

hvz_register_tag_submit:
    pattern: /register_tag
    defaults: { _controller: HvzGameBundle:Game/RegisterTag:index }
    methods: [POST]

# Game\Players Controller
hvz_players:
    pattern: /players
    defaults: { _controller: HvzGameBundle:Game/Players:index }

hvz_tags:
    pattern: /tags
    defaults: { _controller: HvzGameBundle:Game/Players:tags }

# Game\Map Controller
hvz_map:
    pattern: /map/{mode}
    defaults: { _controller: HvzGameBundle:Game/Map:index, mode: "all" }

# Game\Missions Controller
hvz_missions:
    pattern: /missions
    defaults: { _controller: HvzGameBundle:Game/Missions:index }


# Profile Controller
hvz_profile:
    pattern: /profile
    defaults: { _controller: HvzGameBundle:Profile:index, page: 0 }

hvz_profile_edit_clan:
    pattern: /profile/clan/edit
    defaults: { _controller: HvzGameBundle:Profile:editClan }

hvz_profile_submit_clan:
    pattern: /profile/clan/submit
    defaults: { _controller: HvzGameBundle:Profile:editClan }
    methods: [POST]

# Admin\Game Controller
hvz_admin_games:
    pattern: /admin/games
    defaults: { _controller: HvzGameBundle:Admin\Game:index }

hvz_admin_game_add_antivirus:
    pattern: /admin/game/{id}/av/add/{token}
    defaults: { _controller: HvzGameBundle:Admin\Game:addAntiVirus }
    requirements:
        id: \d+

hvz_admin_game_create:
    pattern: /admin/game/create
    defaults: { _controller: HvzGameBundle:Admin\Game:create }

hvz_admin_game_edit:
    pattern: /admin/game/{id}/edit
    defaults: { _controller: HvzGameBundle:Admin\Game:edit }
    requirements:
        id: \d+

hvz_admin_game_delete:
    pattern: /admin/game/{id}/delete/{token}
    defaults: { _controller: HvzGameBundle:Admin\Game:delete }
    requirements:
        id: \d+

# Admin\User Controller
hvz_admin_users_search:
    pattern: /admin/users/search
    defaults: { _controller: HvzGameBundle:Admin\User:search }

hvz_admin_users:
    pattern: /admin/users/{page}
    defaults: { _controller: HvzGameBundle:Admin\User:index, page: 0 }
    requirements:
        id: \d+

hvz_admin_user_edit:
    pattern: /admin/user/{id}/edit
    defaults: { _controller: HvzGameBundle:Admin\User:edit }
    requirements:
        id: \d+

hvz_admin_user_delete:
    pattern: /admin/user/{id}/delete/{token}
    defaults: { _controller: HvzGameBundle:Admin\User:delete }
    requirements:
        id: \d+

# Admin\Profile Controller
hvz_admin_profiles:
    pattern: /admin/profiles/{page}
    defaults: { _controller: HvzGameBundle:Admin\Profile:index, page: 0 }
    requirements:
        page: \d+

hvz_admin_profiles_by_game:
    pattern: /admin/profiles/game/{game}
    defaults: { _controller: HvzGameBundle:Admin\Profile:index }
    requirements:
        game: \d+

hvz_admin_profiles_by_user:
    pattern: /admin/profiles/user/{user}
    defaults: { _controller: HvzGameBundle:Admin\Profile:index }
    requirements:
        user: \d+

hvz_admin_profile_generate:
    pattern: /admin/profile/generate/{id}/{token}
    defaults: { _controller: HvzGameBundle:Admin\Profile:generate }
    requirements:
        id: \d+

hvz_admin_profiles_print:
    pattern: /admin/profiles/game/{game}/print
    defaults: { _controller: HvzGameBundle:Admin\Profile:print }

hvz_admin_profile_view:
    pattern: /admin/profile/{id}/view
    defaults: { _controller: HvzGameBundle:Admin\Profile:view }
    requirements:
        id: \d+

hvz_admin_profile_add_tag:
    pattern: /admin/profile/{id}/tag/add
    defaults: { _controller: HvzGameBundle:Admin\Profile:addTag }
    requirements:
        id: \d+

hvz_admin_profile_give_badge:
    pattern: /admin/profile/{id}/badge/give
    defaults: { _controller: HvzGameBundle:Admin\Profile:giveBadge }
    requirements:
        id: \d+

hvz_admin_profile_give_badge_submit:
    pattern: /admin/profile/{id}/badge/give/{badge}
    defaults: { _controller: HvzGameBundle:Admin\Profile:giveBadge }
    requirements:
        id: \d+

hvz_admin_profile_edit:
    pattern: /admin/profile/{id}/edit
    defaults: { _controller: HvzGameBundle:Admin\Profile:edit }
    requirements:
        id: \d+

hvz_admin_profile_avatar_change:
    pattern: /admin/profile/{id}/avatar/change
    defaults: { _controller: HvzGameBundle:Admin\Profile:changeAvatar }
    requirements:
        id: \d+

hvz_admin_profile_avatar_submit:
    pattern: /admin/profile/{id}/avatar/submit
    defaults: { _controller: HvzGameBundle:Admin\Profile:submitAvatar }
    requirements:
        id: \d+

hvz_admin_profile_delete:
    pattern: /admin/profile/{id}/delete/{token}
    defaults: { _controller: HvzGameBundle:Admin\Profile:delete }
    requirements:
        id: \d+

# Admin\Mission Controller
hvz_admin_missions:
    pattern: /admin/missions
    defaults: { _controller: HvzGameBundle:Admin\Mission:index }

hvz_admin_missions_by_game:
    pattern: /admin/missions/game/{game}
    defaults: { _controller: HvzGameBundle:Admin\Mission:index }
    requirements:
        game: \d+

hvz_admin_mission_edit:
    pattern: /admin/mission/{id}/edit
    defaults: { _controller: HvzGameBundle:Admin\Mission:edit }
    requirements:
        id: \d+

hvz_admin_mission_create:
    pattern: /admin/mission/create
    defaults: { _controller: HvzGameBundle:Admin\Mission:create }

hvz_admin_mission_delete:
    pattern: /admin/mission/{id}/delete/{token}
    defaults: { _controller: HvzGameBundle:Admin\Mission:delete }
    requirements:
        id: \d+

# Admin\Rules Controller
hvz_admin_rules:
    pattern: /admin/rules
    defaults: { _controller: HvzGameBundle:Admin\Rules:index }

hvz_admin_rule_edit:
    pattern: /admin/rule/{id}/edit
    defaults: { _controller: HvzGameBundle:Admin\Rules:edit }
    requirements:
        id: \d+

hvz_admin_rule_create:
    pattern: /admin/rule/create
    defaults: { _controller: HvzGameBundle:Admin\Rules:create }

hvz_admin_rule_delete:
    pattern: /admin/rule/{id}/delete/{token}
    defaults: { _controller: HvzGameBundle:Admin\Rules:delete }
    requirements:
        id: \d+

# Auth Controller
hvz_auth_register:
    pattern: /auth/register
    defaults: { _controller: HvzGameBundle:Auth:register }

hvz_auth_register_code:
    pattern: /auth/register/code
    defaults: { _controller: HvzGameBundle:Auth:registerCode }

hvz_auth_login:
    pattern: /auth/login
    defaults: { _controller: HvzGameBundle:Auth:login }

hvz_auth_login_code:
    pattern: /auth/login/code
    defaults: { _controller: HvzGameBundle:Auth:loginCode }

hvz_auth_logout:
    pattern: /auth/logout/{token}
    defaults: { _controller: HvzGameBundle:Auth:logout }

hvz_error_403:
    pattern: /error/403
    defaults: { _controller: HvzGameBundle:Auth:authError }

hvz_error_active:
    pattern: /error/active
    defaults: { _controller: HvzGameBundle:Auth:activeError }
