# Status Controller
hvz_index:
    pattern: /
    defaults: { _controller: HvzGameBundle:Game/Status:index }

hvz_error_game:
    pattern: /error/game
    defaults: { _controller: HvzGameBundle:Game/Status:gameError }

# Rules Controller
hvz_rules:
    pattern: /rules
    defaults: { _controller: HvzGameBundle:Game/Rules:index }

# Register Tag Controller
hvz_register_tag:
    pattern: /register_tag
    defaults: { _controller: HvzGameBundle:Game/RegisterTag:index }
    methods: [GET]

hvz_register_tag_submit:
    pattern: /register_tag
    defaults: { _controller: HvzGameBundle:Game/RegisterTag:index }
    methods: [POST]

# Players Controller
hvz_players:
    pattern: /players
    defaults: { _controller: HvzGameBundle:Game/Players:index }

hvz_tags:
    pattern: /tags
    defaults: { _controller: HvzGameBundle:Game/Players:tags }

# Map Controller
hvz_map:
    pattern: /map/{mode}
    defaults: { _controller: HvzGameBundle:Game/Map:index, mode: "all" }

# Missions Controller
hvz_missions:
    pattern: /missions
    defaults: { _controller: HvzGameBundle:Game/Missions:index }


# Profile Controller
hvz_profile:
    pattern: /profile
    defaults: { _controller: HvzGameBundle:Profile:index }

hvz_profile_edit_clan:
    pattern: /profile/clan/edit
    defaults: { _controller: HvzGameBundle:Profile:editClan }

hvz_profile_submit_clan:
    pattern: /profile/clan/submit
    defaults: { _controller: HvzGameBundle:Profile:editClan }
    methods: [POST]

# Admin Controller
hvz_admin_games:
    pattern: /admin/games
    defaults: { _controller: HvzGameBundle:Admin:games }

hvz_admin_game_add_antivirus:
    pattern: /admin/game/{id}/av/add/{token}
    defaults: { _controller: HvzGameBundle:Admin:gameAddAntiVirus }
    requirements:
        id: \d+

hvz_admin_game_create:
    pattern: /admin/game/create
    defaults: { _controller: HvzGameBundle:Admin:gameCreate }

hvz_admin_game_edit:
    pattern: /admin/game/{id}/edit
    defaults: { _controller: HvzGameBundle:Admin:gameEdit }
    requirements:
        id: \d+

hvz_admin_game_delete:
    pattern: /admin/game/{id}/delete/{token}
    defaults: { _controller: HvzGameBundle:Admin:gameDelete }
    requirements:
        id: \d+

hvz_admin_users:
    pattern: /admin/users
    defaults: { _controller: HvzGameBundle:Admin:users }

hvz_admin_user_edit:
    pattern: /admin/user/{id}/edit
    defaults: { _controller: HvzGameBundle:Admin:userEdit }
    requirements:
        id: \d+

hvz_admin_user_delete:
    pattern: /admin/user/{id}/delete/{token}
    defaults: { _controller: HvzGameBundle:Admin:userDelete }
    requirements:
        id: \d+

hvz_admin_profile_generate:
    pattern: /admin/profile/generate/{id}/{token}
    defaults: { _controller: HvzGameBundle:Admin:profileGenerate }
    requirements:
        id: \d+

hvz_admin_profiles:
    pattern: /admin/profiles
    defaults: { _controller: HvzGameBundle:Admin:profiles }

hvz_admin_profiles_print:
    pattern: /admin/profiles/game/{game}/print
    defaults: { _controller: HvzGameBundle:Admin:profilesPrint }

hvz_admin_profiles_by_game:
    pattern: /admin/profiles/game/{game}
    defaults: { _controller: HvzGameBundle:Admin:profiles }
    requirements:
        game: \d+

hvz_admin_profiles_by_user:
    pattern: /admin/profiles/user/{user}
    defaults: { _controller: HvzGameBundle:Admin:profiles }
    requirements:
        user: \d+

hvz_admin_profile_view:
    pattern: /admin/profile/{id}/view
    defaults: { _controller: HvzGameBundle:Admin:profileView }
    requirements:
        id: \d+

hvz_admin_profile_add_tag:
    pattern: /admin/profile/{id}/tag/add
    defaults: { _controller: HvzGameBundle:Admin:profileAddTag }
    requirements:
        id: \d+

hvz_admin_profile_give_badge:
    pattern: /admin/profile/{id}/badge/give
    defaults: { _controller: HvzGameBundle:Admin:profileGiveBadge }
    requirements:
        id: \d+

hvz_admin_profile_give_badge_submit:
    pattern: /admin/profile/{id}/badge/give/{badge}
    defaults: { _controller: HvzGameBundle:Admin:profileGiveBadge }
    requirements:
        id: \d+

hvz_admin_profile_edit:
    pattern: /admin/profile/{id}/edit
    defaults: { _controller: HvzGameBundle:Admin:profileEdit }
    requirements:
        id: \d+

hvz_admin_profile_avatar_change:
    pattern: /admin/profile/{id}/avatar/change
    defaults: { _controller: HvzGameBundle:Admin:profileChangeAvatar }
    requirements:
        id: \d+

hvz_admin_profile_avatar_submit:
    pattern: /admin/profile/{id}/avatar/submit
    defaults: { _controller: HvzGameBundle:Admin:profileSubmitAvatar }
    requirements:
        id: \d+

hvz_admin_profile_delete:
    pattern: /admin/profile/{id}/delete/{token}
    defaults: { _controller: HvzGameBundle:Admin:profileDelete }
    requirements:
        id: \d+

hvz_admin_missions:
    pattern: /admin/missions
    defaults: { _controller: HvzGameBundle:Admin:missions }

hvz_admin_missions_by_game:
    pattern: /admin/missions/game/{game}
    defaults: { _controller: HvzGameBundle:Admin:missions }
    requirements:
        game: \d+

hvz_admin_mission_edit:
    pattern: /admin/mission/{id}/edit
    defaults: { _controller: HvzGameBundle:Admin:missionEdit }
    requirements:
        id: \d+

hvz_admin_mission_create:
    pattern: /admin/mission/create
    defaults: { _controller: HvzGameBundle:Admin:missionCreate }

hvz_admin_mission_delete:
    pattern: /admin/mission/{id}/delete/{token}
    defaults: { _controller: HvzGameBundle:Admin:missionDelete }
    requirements:
        id: \d+

hvz_admin_rules:
    pattern: /admin/rules
    defaults: { _controller: HvzGameBundle:Admin:rules }

hvz_admin_rule_edit:
    pattern: /admin/rule/{id}/edit
    defaults: { _controller: HvzGameBundle:Admin:ruleEdit }
    requirements:
        id: \d+

hvz_admin_rule_create:
    pattern: /admin/rule/create
    defaults: { _controller: HvzGameBundle:Admin:ruleCreate }

hvz_admin_rule_delete:
    pattern: /admin/rule/{id}/delete/{token}
    defaults: { _controller: HvzGameBundle:Admin:ruleDelete }
    requirements:
        id: \d+


# Auth Controller
hvz_auth_register:
    pattern: /auth/register
    defaults: { _controller: HvzGameBundle:Auth:register }

hvz_auth_register_code:
    pattern: /auth/register/code
    defaults: { _controller: HvzGameBundle:Auth:registerCode }

hvz_auth_login:
    pattern: /auth/login
    defaults: { _controller: HvzGameBundle:Auth:login }

hvz_auth_login_code:
    pattern: /auth/login/code
    defaults: { _controller: HvzGameBundle:Auth:loginCode }

hvz_auth_logout:
    pattern: /auth/logout/{token}
    defaults: { _controller: HvzGameBundle:Auth:logout }

hvz_error_403:
    pattern: /error/403
    defaults: { _controller: HvzGameBundle:Auth:authError }

hvz_error_active:
    pattern: /error/active
    defaults: { _controller: HvzGameBundle:Auth:activeError }
