parameters:
#    hvz_game.example.class: Hvz\GameBundle\Example

services:

    google_oauth.security.authentication.listener:
        class:  Hvz\GameBundle\Security\Firewall\GoogleOAuthListener
        arguments: ["@security.context", "@security.authentication.manager"]

    hvz.tag_generator:
        class: Hvz\GameBundle\Services\TagGeneratorService
        arguments: ["@doctrine.orm.entity_manager"]

    hvz.navigation:
        class: Hvz\GameBundle\Services\NavigationService
        arguments: ["@router", "@security.context"]

    hvz.badges:
        class: Hvz\GameBundle\Services\BadgeService
        arguments: ["@doctrine.orm.entity_manager"]

    hvz.oauth.settings:
        class: Hvz\GameBundle\Services\OAuthSettings
        arguments: [""]

    hvz.oauth.google:
        class: Hvz\GameBundle\Services\GoogleOAuthService
        arguments: ["@hvz.oauth.settings"]

    google_oauth.security.authentication.provider:
        class:  Hvz\GameBundle\Security\Authentication\Provider\GoogleOAuthProvider
        arguments: ["", "@hvz.oauth.google"]
