<?php

namespace Hvz\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AntiVirusTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AntiVirusTagRepository extends EntityRepository
{
    public function findOneByGameAndTag($game, $tag)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $query = $qb->select('av')
                    ->from('HvzGameBundle:AntiVirusTag', 'av')
                    ->where('av.game = :game')
                    ->andWhere('av.tag = :tag')
                    ->setParameter('game', $game)
                    ->setParameter('tag', $tag)
                    ->getQuery();

        return $query->getOneOrNullResult();
    }
}
