<?php

namespace Hvz\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
	public function findCurrentGame($date = null)
	{
		if($date == null)
			$date = date_create('now');

		$qb = $this->getEntityManager()->createQueryBuilder();
		$query = $qb->select('g')
					->from('HvzGameBundle:Game', 'g')
					->where('g.startDate <= :date')
					->andWhere('g.endDate >= :date')
					->setParameter('date', $date)
					->getQuery();

		$result = $query->getResult();
		return $result == null ? null : $result[0];
	}

	public function findNextGame($date = null)
	{
		if($date == null)
			$date = date_create('now');

		$qb = $this->getEntityManager()->createQueryBuilder();
		$query = $qb->select('g')
					->from('HvzGameBundle:Game', 'g')
					->where('g.startDate >= :date')
					->setParameter('date', $date)
					->getQuery();

		$result = $query->getResult();
		return $result == null ? null : $result[0];
	}

	public function findAllOrderedByStartDate()
	{
		return $this->getEntityManager()->createQuery('SELECT g from HvzGameBundle:Game g ORDER BY g.startDate ASC')->getResult();
	}
}
