<?php

namespace Hvz\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InfectionSpreadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfectionSpreadRepository extends EntityRepository
{
	public function findByGameOrderedByTime($game)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		$query = $qb->select('s')
					->from('HvzGameBundle:InfectionSpread', 's')
					->where('s.game = :game')
					->orderBy('s.time', 'DESC')
					->setParameter('game', $game)
					->getQuery();

		return $query->getResult();
	}

	public function findPageByGameOrderedByTime($game, $page, $maxPerPage = 10)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		$query = $qb->select('s')
					->from('HvzGameBundle:InfectionSpread', 's')
					->where('s.game = :game')
					->orderBy('s.time', 'DESC')
					->setParameter('game', $game)
					->getQuery()
					->setMaxResults($maxPerPage)
					->setFirstResult($page * $maxPerPage);

		return $query->getResult();
	}

	public function findByZombieOrderedByTime($game, $zombie)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		$query = $qb->select('s')
					->from('HvzGameBundle:InfectionSpread', 's')
					->where('s.game = :game')
					->andWhere('s.zombie = :zombie')
					->orderBy('s.time', 'DESC')
					->setParameter('game', $game)
					->setParameter('zombie', $zombie)
					->getQuery();

		return $query->getResult();
	}

	public function findForKillstreak($zombie)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		$query = $qb->select('s')
					->from('HvzGameBundle:InfectionSpread', 's')
					->where('s.game = :game')
					->andWhere('s.zombie = :zombie')
					->andWhere('s.time BETWEEN :start AND :end')
					->setParameter('game', $zombie->getGame())
					->setParameter('zombie', $zombie)
					->setParameter('start', new \DateTime('-1 hour'))
					->setParameter('end', new \DateTime())
					->getQuery();

		return $query->getResult();
	}

	public function findPreviousDay($game)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		$query = $qb->select('s')
					->from('HvzGameBundle:InfectionSpread', 's')
					->where('s.game = :game')
					->andWhere('s.time BETWEEN :start AND :end')
					->orderBy('s.time', 'DESC')
					->setParameter('game', $game)
					->setParameter('start', new \DateTime('-1 day'))
					->setParameter('end', new \DateTime())
					->getQuery();

		return $query->getResult();
	}
}
