<?php

namespace Hvz\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MissionRepository extends EntityRepository
{
	public function findAllOrderedByDate()
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		$query = $qb->select('m')
					->from('HvzGameBundle:Mission', 'm')
					->orderBy('m.postdate', 'DESC')
					->getQuery();
		return $query->getResult();
	}

	public function findByGameOrderedByDate($game)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		$query = $qb->select('m')
					->from('HvzGameBundle:Mission', 'm')
					->where('m.game = :game')
					->orderBy('m.postdate', 'DESC')
					->setParameter('game', $game)
					->getQuery();
		return $query->getResult();
	}

	public function findPostedOrderedByDate($game)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		$query = $qb->select('m')
					->from('HvzGameBundle:Mission', 'm')
					->where('m.game = :game')
					->andWhere('m.postdate <= :date_now')
					->orderBy('m.postdate', 'DESC')
					->setParameter('game', $game)
					->setParameter('date_now', date_create("now"))
					->getQuery();

		return $query->getResult();
	}

	public function findPostedByTeamOrderedByDate($game, $team)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		$query = $qb->select('m')
					->from('HvzGameBundle:Mission', 'm')
					->where('m.game = :game')
					->andWhere('m.team = :team')
					->andWhere('m.postdate <= :date_now')
					->orderBy('m.postdate', 'DESC')
					->setParameter('game', $game)
					->setParameter('team', $team)
					->setParameter('date_now', date_create("now"))
					->getQuery();

		return $query->getResult();
	}
}
