<?php

namespace Hvz\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerTagRepository extends EntityRepository
{
	public function findByProfile($profile)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		$query = $qb->select('t')
					->from('HvzGameBundle:PlayerTag', 't')
					->Andwhere('t.profile = :profile')
					->setParameter('profile', $profile)
					->getQuery();

		return $query->getResult();
	}
}
