<?php

namespace Hvz\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
	public function findAllOrderedByDate()
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		$query = $qb->select('p')
					->from('HvzGameBundle:Post', 'p')
					->orderBy('p.postdate', 'DESC')
					->getQuery();
		return $query->getResult();
	}
}
