<?php

namespace Hvz\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends EntityRepository
{
	public function findByGameAndUser($game, $user)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		$query = $qb->select('p')
					->from('HvzGameBundle:Profile', 'p')
					->where('p.user = :user')
					->andWhere('p.game = :game')
					->setParameter('user', $user)
					->setParameter('game', $game)
					->getQuery();

		$result = $query->getResult();
		return $result == null ? null : $result[0];
	}

	public function findActive($game)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		$query = $qb->select('p')
					->from('HvzGameBundle:Profile', 'p')
					->where('p.active = true')
					->andWhere('p.game = :game')
					->setParameter('game', $game)
					->getQuery();

		return $query->getResult();
	}

	public function findActiveByTeam($game, $team)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		$query = $qb->select('p')
					->from('HvzGameBundle:Profile', 'p')
					->where('p.active = true')
					->andWhere('p.team = :team')
					->andWhere('p.game = :game')
					->setParameter('team', $team)
					->setParameter('game', $game)
					->getQuery();

		return $query->getResult();
	}

	public function findActiveZombies($game)
	{
		return $this->findActiveByTeam($game, User::TEAM_ZOMBIE);
	}

	public function findActiveHumans($game)
	{
		return $this->findActiveByTeam($game, User::TEAM_HUMAN);
	}

	public function findActiveOrderedByNumberTaggedAndTeam($game)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		$query = $qb->select('p')
					->from('HvzGameBundle:Profile', 'p')
					->where('p.active = true')
					->andWhere('p.game = :game')
					->orderBy('p.numberTagged', 'DESC')
					->orderBy('p.team', 'DESC')
					->setParameter('game', $game)
					->getQuery();

		return $query->getResult();
	}
	
	public function findActiveOrderedByCustom($game, $sortBy)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		$query = $qb->select('p, -p.clan as HIDDEN tmpClan')
					->from('HvzGameBundle:Profile', 'p')
					->where('p.active = true')
					->andWhere('p.game = :game')
					->setParameter('game', $game);
		
		switch($sortBy)
		{
			case "clan":
				$query->orderBy('tmpClan', 'ASC');
				break;
		}
		
		$query = $query->getQuery();

		return $query->getResult();
	}
}
