<?php

namespace Hvz\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RuleRepository extends EntityRepository
{
	public function findAllOrderedByPosition()
	{
		return $this->getEntityManager()->createQuery('SELECT r from HvzGameBundle:Rule r ORDER BY r.position ASC')->getResult();
	}
}
