# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    action_log:
        class: AppBundle\Service\ActionLog
        arguments: ["@doctrine.orm.entity_manager"]

    id_generator:
        class: AppBundle\Service\IdGenerator
        arguments: ["@doctrine.orm.entity_manager"]

    badge_registry:
        class: AppBundle\Service\BadgeRegistry
        arguments: ["@doctrine.orm.entity_manager"]

    google_oauth_client:
        class: AppBundle\Service\GoogleOAuthClient
        arguments: ["%google_client_id%", "%google_client_secret%", "%google_application_name%"]