# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

    google_oauth.client:
        class: AppBundle\Service\GoogleOAuthClient
        arguments: ["%google_client_id%", "%google_client_secret%", "%google_application_name%"]

    google_oauth.provider:
        class: AppBundle\Security\Authentication\Provider\GoogleOAuthProvider

    action_log:
        class: AppBundle\Service\ActionLog

    id_generator:
        class: AppBundle\Service\IdGenerator

    badge_registry:
        class: AppBundle\Service\BadgeRegistry

    game_status:
        class: AppBundle\Service\GameStatus
        arguments: ["@doctrine.orm.entity_manager", "%hvz_game_start%", "%hvz_game_end%"]