<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AntiVirusIdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AntiVirusIdRepository extends EntityRepository
{
    public function findHasUsedAntivirus($user)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $query = $qb->select('count(av)')
            ->from('AppBundle:AntiVirusId', 'av')
            ->where('av.user = :user')
            ->setParameter('user', $user)
            ->getQuery();

        return $query->getSingleScalarResult() > 0;
    }
}
