<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InfectionSpreadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfectionSpreadRepository extends EntityRepository
{
}
