<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findActiveCount($team = -1)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $query = $qb->select('count(u)')
            ->from('AppBundle:User', 'u')
            ->where('u.active = true');
        if($team >= 0)
        {
            $qb = $qb->andWhere('u.team = :team')
                ->setParameter('team', $team);
        }

        $qb = $qb->getQuery();
        return $qb->getSingleScalarResult();
    }
}
